### ISSUE TITLE
Build error "No such module 'NPOStream' @ TVCollection.swift

### ISSUE THREAD

**Issue by sjogro** [hollanderbart/NPO-Live#1]
//
//  ViewController.swift
//  NPO Live
//
//  Created by Maurice van Breukelen on 21-11-15.
//  Copyright © 2015 Maurice van Breukelen. All rights reserved.
//

import UIKit
import AVKit
import NPOStream     **<--- No such module 'NPOStream'**

**Comment by hollanderbart** [comment]
Sorry voor deze build error. Er komt een pull request aan om dit op te lossen.

**Comment by hollanderbart** [comment]
Fixed in #2

**Comment by sjogro** [comment]
Ik krijg nog steeds dezelfde build error in v1.1 :-(

**Comment by hollanderbart** [comment]
Met het openen van de `NPO Live.xcworkspace` zou het moeten lukken. Zou jij dit willen proberen?

**Comment by sjogro** [comment]
Dat werkte inderdaad. Heb de app kunnen installeren op ATV4K maar de app crasht helaas wel regelmatig bij het laden van alle (live) thumbnails.

**Comment by hollanderbart** [comment]
Ga ik onderzoeken op oplossen!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hollanderbart** [comment]
Hi @sjogro, zou jij het met de laatste versie (1.1.0) willen proberen of het crashen nu verholpen is?
