### ISSUE TITLE
NPO Live app niet compatibel met Swift 3

### ISSUE THREAD

**Issue by rvlak** [hollanderbart/NPO-Live#13]
Beste Bart / lezer,

Sinds kort heb ik een Apple TV4 en ik wil daarop heel graag de handige app 'NPO Live' sideloaden. Maar jammer genoeg blijkt de app niet compatible met de nieuwste versie van Xcode (v9), doordat er nog source code in zit die geschreven is in Swift 2.x. 

Bij het compileren in Xcode 9 krijg je [deze foutmelding](https://www.dropbox.com/s/ewz3lu7j1tbnpes/Unsupported%20Swift%20version%20in%20XCode%209%20voor%20NPO%20Live.png?dl=0): 

Ik heb vervolgens geprobeerd om de app in Xcode 8.2.1 te laden en daar eerst de betreffende code te converteren naar Swift 3. Maar dat is niet mogelijk, omdat de tvOS versies niet overeenkomen. Je krijgt dan [deze melding](https://www.dropbox.com/s/ac66q97g0jv3x5v/tvOS%20not%20compatible%20in%20XCode%208.2.1.%20voor%20NPO%20Live.png?dl=0)

Heb jij hier misschien een oplossing voor?

![tvos not compatible in xcode 8 2 1 voor npo live](https://user-images.githubusercontent.com/16000518/34815614-455eea5c-f6b2-11e7-9eaa-92b1303d396a.png)
![unsupported swift version in xcode 9 voor npo live](https://user-images.githubusercontent.com/16000518/34815615-457901a8-f6b2-11e7-8842-8998c892e8bb.png)

**Comment by hollanderbart** [comment]
Sorry voor de late reactie. Zie net pas dat je een issue hebt aangemaakt.
Ik zal hier naar kijken en zo mogelijk dit probleem oplossen.

**Comment by rvlak** [comment]
Beste Bart,

Dank!

Met vriendelijke groet,

René

**Comment by hollanderbart** [comment]
Hi Rene,
Ik krijg dezelfde melding niet omdat de huidige Swift versie 4 is. Dat jij nog een melding krijgt dat er nog sommige code in Swift 2 geschreven is, heeft waarschijnlijk te maken met dat jij nog een oude versie gebruikt.
Zou jij het project van deze repository willen downloaden en het opnieuw proberen?

**Comment by rvlak** [comment]
Hi Bart, 

Dank voor je reactie, ik heb de nieuwste Xcode versie nog een keer gedownload, en de nieuwste versie van het project en nu werkt het! Heel erg fijn. 

Hartelijke groet, René
