### ISSUE TITLE
Meeste streams niet werkend na openen

### ISSUE THREAD

**Issue by djrobinfm** [hollanderbart/NPO-Live#14]
In het homescreen laden de meeste streams wel allemaal (behalve NPO 2 zoals op de afbeelding te zien is), maar na het kiezen blijft de stream vaak oneindig laden. Gaat dus niet om de geluidsloze streams in het homescreen, maar de daadwerkelijke streams na het kiezen.
![screen shot 2018-03-20 at 16 35 50](https://user-images.githubusercontent.com/37588740/37665088-ce3c2742-2c5c-11e8-9ce7-b6c61b669495.png)
Het idee achter deze app en de interface vind ik echt te gek dus hoop dat het makkelijk opgelost kan worden.

**Comment by FokkeZB** [comment]
Wat mij betreft tonen we op dit scherm gewoon alleen de logos? Als ik wil zien wat er op een kanaal is kijk ik wel in de NPO app gids. Al die streams laden als preview maakt het scherm echt enorm traag is mijn ervaring.

**Comment by djrobinfm** [comment]
Nu ik mijn issue teruglees zie ik dat het lijkt alsof ik bedoel dat ik al die streams op het homescreen werkend wil hebben. Dat boeit mij ook vrij weinig, al ziet het er wel mooi uit natuurlijk. Ik bedoel de streams die geladen worden _na_ het kiezen van een zender.

**Comment by hollanderbart** [comment]
Het idee is inderdaad om live alle uitzendingen te kunnen zien. Dit geeft wat mij betreft de beste gebruiksvriendelijkheid. Echter moet dit natuurlijk wel goed functioneren. 
Ik ben hier al mee bezig door de live uitzendingen te beperken tot alleen het moment waarneer je over een uitzending(cell) heen navigeert. Dit brengt hopelijk de gewenste prestatie verbetering met behoud van goede gebruiksvriendelijkheid.
