### ISSUE TITLE
Unable to run on Apple TV4

### ISSUE THREAD

**Issue by kerkenit** [hollanderbart/NPO-Live#3]
I'm trying to run it on an Apple TV 4 but it gives me several errors:

Ditto /Users/ikke/Library/Developer/Xcode/DerivedData/NPO_Live-doumwqbuodkorwezpzatrlkdfmqa/Build/Intermediates.noindex/NPO\ Live.build/Debug-appletvos/NPO\ Live.build/DerivedSources/NPO_Live-Swift.h /Users/ikke/Library/Developer/Xcode/DerivedData/NPO_Live-doumwqbuodkorwezpzatrlkdfmqa/Build/Intermediates.noindex/NPO\ Live.build/Debug-appletvos/NPO\ Live.build/Objects-normal/arm64/NPO_Live-Swift.h
    cd /Users/ikke/Downloads/NPO-Live-master
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /usr/bin/ditto -rsrc /Users/ikke/Library/Developer/Xcode/DerivedData/NPO_Live-doumwqbuodkorwezpzatrlkdfmqa/Build/Intermediates.noindex/NPO\ Live.build/Debug-appletvos/NPO\ Live.build/Objects-normal/arm64/NPO_Live-Swift.h /Users/ikke/Library/Developer/Xcode/DerivedData/NPO_Live-doumwqbuodkorwezpzatrlkdfmqa/Build/Intermediates.noindex/NPO\ Live.build/Debug-appletvos/NPO\ Live.build/DerivedSources/NPO_Live-Swift.h

ditto: can't get real path for source '/Users/ikke/Library/Developer/Xcode/DerivedData/NPO_Live-doumwqbuodkorwezpzatrlkdfmqa/Build/Intermediates.noindex/NPO Live.build/Debug-appletvos/NPO Live.build/Objects-normal/arm64/NPO_Live-Swift.h'

Ld /Users/ikke/Library/Developer/Xcode/DerivedData/NPO_Live-doumwqbuodkorwezpzatrlkdfmqa/Build/Products/Debug-appletvos/NPO\ Live.app/NPO\ Live normal arm64
    cd /Users/ikke/Downloads/NPO-Live-master
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export TVOS_DEPLOYMENT_TARGET=11.0
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS11.0.sdk -L/Users/ikke/Library/Developer/Xcode/DerivedData/NPO_Live-doumwqbuodkorwezpzatrlkdfmqa/Build/Products/Debug-appletvos -F/Users/ikke/Library/Developer/Xcode/DerivedData/NPO_Live-doumwqbuodkorwezpzatrlkdfmqa/Build/Products/Debug-appletvos -F/Users/ikke/Library/Developer/Xcode/DerivedData/NPO_Live-doumwqbuodkorwezpzatrlkdfmqa/Build/Products/Debug-appletvos/NPOStream -F/Users/ikke/Downloads/NPO-Live-master/NPO\ Live -filelist /Users/ikke/Library/Developer/Xcode/DerivedData/NPO_Live-doumwqbuodkorwezpzatrlkdfmqa/Build/Intermediates.noindex/NPO\ Live.build/Debug-appletvos/NPO\ Live.build/Objects-normal/arm64/NPO\ Live.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -mtvos-version-min=11.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/ikke/Library/Developer/Xcode/DerivedData/NPO_Live-doumwqbuodkorwezpzatrlkdfmqa/Build/Intermediates.noindex/NPO\ Live.build/Debug-appletvos/NPO\ Live.build/Objects-normal/arm64/NPO\ Live_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fembed-bitcode-marker -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/appletvos -Xlinker -add_ast_path -Xlinker /Users/ikke/Library/Developer/Xcode/DerivedData/NPO_Live-doumwqbuodkorwezpzatrlkdfmqa/Build/Intermediates.noindex/NPO\ Live.build/Debug-appletvos/NPO\ Live.build/Objects-normal/arm64/NPO_Live.swiftmodule -framework NPOStream -framework Pods_NPO_Live -Xlinker -dependency_info -Xlinker /Users/ikke/Library/Developer/Xcode/DerivedData/NPO_Live-doumwqbuodkorwezpzatrlkdfmqa/Build/Intermediates.noindex/NPO\ Live.build/Debug-appletvos/NPO\ Live.build/Objects-normal/arm64/NPO\ Live_dependency_info.dat -o /Users/ikke/Library/Developer/Xcode/DerivedData/NPO_Live-doumwqbuodkorwezpzatrlkdfmqa/Build/Products/Debug-appletvos/NPO\ Live.app/NPO\ Live

ld: warning: directory not found for option '-F/Users/ikke/Library/Developer/Xcode/DerivedData/NPO_Live-doumwqbuodkorwezpzatrlkdfmqa/Build/Products/Debug-appletvos/NPOStream'
ld: file not found: /Users/ikke/Library/Developer/Xcode/DerivedData/NPO_Live-doumwqbuodkorwezpzatrlkdfmqa/Build/Intermediates.noindex/NPO Live.build/Debug-appletvos/NPO Live.build/Objects-normal/arm64/String+Extension.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/ikke/Library/Developer/Xcode/DerivedData/NPO_Live-doumwqbuodkorwezpzatrlkdfmqa/Build/Intermediates.noindex/NPO\ Live.build/Debug-appletvos/NPO\ Live.build/Script-8B16D6343422013507124AC7.sh
    cd /Users/ikke/Downloads/NPO-Live-master
    /bin/sh -c \"/Users/ikke/Library/Developer/Xcode/DerivedData/NPO_Live-doumwqbuodkorwezpzatrlkdfmqa/Build/Intermediates.noindex/NPO\ Live.build/Debug-appletvos/NPO\ Live.build/Script-8B16D6343422013507124AC7.sh\"

mkdir -p /Users/ikke/Library/Developer/Xcode/DerivedData/NPO_Live-doumwqbuodkorwezpzatrlkdfmqa/Build/Products/Debug-appletvos/NPO Live.app/Frameworks
rsync -av --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "" "/Users/ikke/Library/Developer/Xcode/DerivedData/NPO_Live-doumwqbuodkorwezpzatrlkdfmqa/Build/Products/Debug-appletvos/NPO Live.app/Frameworks"
building file list ... done
.DS_Store
NPO Live.xcodeproj/project.xcworkspace/xcuserdata/ikke.xcuserdatad/
NPO Live.xcodeproj/project.xcworkspace/xcuserdata/ikke.xcuserdatad/UserInterfaceState.xcuserstate
Pods/

sent 23818 bytes  received 76 bytes  47788.00 bytes/sec
total size is 6105329  speedup is 255.52
Code Signing /Users/ikke/Library/Developer/Xcode/DerivedData/NPO_Live-doumwqbuodkorwezpzatrlkdfmqa/Build/Products/Debug-appletvos/NPO Live.app/Frameworks/NPOStream.framework with Identity iPhone Developer: Gerardus Bruggink (86JWV93C3C)
/usr/bin/codesign --force --sign DE636949257FEB0FBBFC93BDC801DE1F8CEA9217  --preserve-metadata=identifier,entitlements '/Users/ikke/Library/Developer/Xcode/DerivedData/NPO_Live-doumwqbuodkorwezpzatrlkdfmqa/Build/Products/Debug-appletvos/NPO Live.app/Frameworks/NPOStream.framework'
/Users/ikke/Library/Developer/Xcode/DerivedData/NPO_Live-doumwqbuodkorwezpzatrlkdfmqa/Build/Products/Debug-appletvos/NPO Live.app/Frameworks/NPOStream.framework: No such file or directory

**Comment by hollanderbart** [comment]
Thanks for reporting the errors. Could you specify which Xcode version you're using?
You could try to clean your build folder using Product -> Clean. After cleaning you can try to rebuild the project. Could you let me know if this works?

**Comment by hollanderbart** [comment]
I'll close this issue because lack of activity. Please reopen when the issue still exists.
